testauth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.contrib.auth import logout
from googleauth import views
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit', views.update_profile, name='edit'),
    path('list', views.users_list, name='list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

googleauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<username>/<username>.extention(.jpg/.png)
    extention = filename.split('.')
    return '{0}/{1}.{2}'.format(instance.user.username, instance.user.username, extention[1])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    pic = models.ImageField(upload_to=user_directory_path, blank=True, default='/default.png')

    def __str__(self):
        return '%s' % (self.user.username)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

googleauth/forms.py
from .models import Profile
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['email'].label = 'Электронная почта'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'pic')

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['bio'].label = 'Информация о себе'
        self.fields['pic'].label = 'Изображение'

googleauth/views.py
from django.shortcuts import render
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .forms import UserForm, ProfileForm
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.template import loader
from django.contrib.auth.decorators import login_required


def index(request):
    context = {
        'users': Profile.objects
        if request.user.is_authenticated else []
    }

    return render(request, 'googleauth/index.html', context)


def users_list(request):
    users_list = Profile.objects.order_by('-user')
    context = {
        'users_list': users_list,
    }
    return render(request, 'googleauth/list.html', context)


@login_required(login_url='/')
def update_profile(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect('/')
        else:
            user_form = UserForm()
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'googleauth/edit.html', {'user_form': user_form, 'profile_form': profile_form})

googleauth/templates/googleauth/base.html
{% load static %}
<html>
  <head>
	<link rel="stylesheet" type="text/css" href="{% static 'googleauth/style.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block title %}
	<title>Главная страница</title>
	{% endblock %}
  </head>
  <body>
	<div class='layout'>		  
		{% block content %}
		{% endblock %}		
	</div>
	{% block script %}
	{% endblock %}
  </body>
</html>

googleauth/templates/googleauth/edit.html
{% extends 'googleauth/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
	<title>Страница редактирования</title>
{% endblock %}

{% block content %}
<div class='layout__item'>
	<a href="{% url 'index' %}"><h3>Назад</h3></a>
	<a href="{% url 'list' %}"><h3>Список пользователей</h3></a>
	<a href="{% url 'logout' %}"><h3>Выйти</h3></a>
</div>
<div class='list__item'>

	<form method="post" enctype="multipart/form-data" class="uniForm">
		{% csrf_token %}
	
		{{ user_form|crispy }}
		{{ profile_form|crispy }}
		
		{% if user.profile.pic %} 
			<div id="image_uploads" class='field' ></div>
			<img class='avatar' src ="{{ user.profile.pic.url }}" ,  width="150px">
		{% endif %}
	
		<p id="previewText" style="display: none;">Загруженное изображение</p>
		<img class='avatar' id="preview" src="http://placehold.it/180" style="display: none;" alt="new image"  />

		<input type="submit" class='submit' value="Сохранить">
	</form>
</div>

{% endblock %}

{% block script %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script>
		$( "#id_pic" ).change(function() {
			readURL(this)
		});

		function readURL(input) {
			console.log('input', input)
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#preview').attr('src', e.target.result);
					$('#preview').css("display","block")
					$('#previewText').css("display","block")	
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
  </script> 
{% endblock %}

googleauth/templates/googleauth/index.html
{% extends 'googleauth/base.html' %}
{% load static %}
{% block content %}
	<div class=''>
		{% if user.is_authenticated %}

		<div class='layout__item'>
			<a href="{% url 'list' %}"><h3>Список пользователей</h3></a>
			<a href="{% url 'logout' %}"><h3>Выйти</h3></a>
		</div>
				
		<div class='list__item'>
			<div class='m-r-50'>
				{% if user.profile.pic %}
				<div class='field'><img class='avatar' src ="{{ user.profile.pic.url }}", width="200px"></b></div>
				<a href="{% url 'edit' %}">Редактировать профиль</a>
				
				{% else %}
				<div class='field'>
					<img class='avatar' src ="{{ MEDIA_URL }}/default.png", width="150px"></b></div>
					<a href="{% url 'edit' %}">Редактировать профиль</a>
				{% endif %}
			</div>
			<div>
				<h1 class='m-t-0'>{{user.username}}</h1>
				{% if user.first_name %}
					<p>{{ user.first_name }}</p>
				{% endif %}
				{% if user.last_name %}
					<p>{{ user.last_name }}</p>
				{% endif %}
				{% if user.profile.bio %}
					<p>{{ user.profile.bio }}</p>
				{% endif %}
			</div>
		</div>
	{% else %}
	<div class='card'>
		<div class='auth'>
			<img class='icon' src="{% static 'googleauth/google.png' %}" alt="Google">
			<a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
				<h2>Войти c помощью Google</h2>
			</a>
		</div>
		<div class='auth'>
			<img class='icon' src="{% static 'googleauth/github.png' %}" alt="github">
			<a class="btn btn-primary" href="{% url 'social:begin' 'github' %}">
				<h2>Войти c помощью Github</h2>
			</a>
		</div>
	</div>
	
	{% endif %}
	</div>
 {% endblock %}

googleauth/templates/googleauth/list.html
{% extends 'googleauth/base.html' %}
{% load static %}

{% block title %}
	<title>Список пользователей</title>
{% endblock %}

{% block content %}
	<div class='layout__item'>
		<a href="{% url 'index' %}"><h3>На главную</h3></a>
		<a href="{% url 'logout' %}"><h3>Выйти</h3></a>
	</div>
	<div>
		{% if users_list %}
			<div class='list'>
			{% for user in users_list %}
				<div class='list__item'>
					<div class='m-r-50'>
						{% if user.pic %} 
							<img class='avatar' src ="{{ MEDIA_URL }}{{ user.pic }}" ,width="200px">
						{% else %}
							<img class='avatar' src ="{{ MEDIA_URL }}/default.png" , width="200px">
						{% endif %}
					</div>
					<div>
						<h1 class='m-t-0'>{{user.user.username}}</h1>
						<p>{{ user.user.first_name }}</p>
						<p>{{ user.user.last_name }}</p>
						<p>{{ user.bio }}</p>
					</div>
				</div>
			{% endfor %}
			</div>
		{% else %}
			<p>No items are available.</p>
		{% endif %}
	</div>	
 {% endblock %}